name: Plugin Release CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release WP Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build Plugin
        run: |
          zip -r spromoter-social-reviews-for-woocommerce.zip .

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: spromoter-social-reviews-for-woocommerce.zip
          token: ${{ secrets.TOKEN }}
          tag: v.1.0.0.0


