name: Plugin Release CI/CD

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release WP Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Compression
        run: |
          zip -r spromoter-social-reviews-for-woocommerce.zip .

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "spromoter-social-reviews-for-woocommerce.zip"
          token: ${{ secrets.TOKEN }}
