name: Plugin Release CI/CD

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release WP Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Compression
        run: |
          mkdir -p spromoter-social-reviews-for-woocommerce
          rsync -av --progress ./* spromoter-social-reviews-for-woocommerce/ --exclude="build.sh" --exclude="spromoter-social-reviews-for-woocommerce.zip" --exclude="spromoter-social-reviews-for-woocommerce"
          zip -r spromoter-social-reviews-for-woocommerce.zip ./spromoter-social-reviews-for-woocommerce
          rm -rf spromoter-social-reviews-for-woocommerce

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "spromoter-social-reviews-for-woocommerce.zip"
