name: Plugin Release CI/CD

on:
  release:
    types: created

jobs:
  build:
    name: Release WP Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: spromoter-social-reviews-for-woocommerce.zip
          path: .

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: spromoter-social-reviews-for-woocommerce.zip


