name: Plugin Release CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release WP Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: dist
          token: ${{ secrets.TOKEN }}
          tag: ${{ steps.version.outputs.tag }}


