name: Plugin Release CI/CD

on:
  release:
    types:
      - created

jobs:
  build:
    name: Release WP Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build Plugin
        run: |
          zip -r spromoter-social-reviews-for-woocommerce.zip .

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: spromoter-social-reviews-for-woocommerce.zip
          token: ${{ secrets.TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          release_name: ${{ github.event.release.name }}

      - name: Get Release ID
        run: echo "Release ID - ${{ steps.create_release.outputs.id }}"
