name: Plugin Release CI/CD

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release WP Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        permissions:
        contents: write

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "includes,/assets/,uninstall.php,spromoter.php"
          token: ${{ secrets.TOKEN }}
